lambdaProps:
  checkBillCron: 0 22 ? * SUN *
  # gcpBillTableId: 'weighty-works-430022-u8.sample_billing.gcp_billing_export_v1_01CB25_64E872_28B129'
  gcpBillTableId: 'ctg-storage.bigquery_billing_export.gcp_billing_export_v1_01150A_B8F62B_47D999' # gcp sample billing data for query
  vaultUrl: http://vault.cmdlab-sandpit3.cmdlabs.com.au:8200
  vaultAWSRole: 'aws/sandpit3/roles/lambda_role'
  vaultGCPRoleSet: 'gcp/carlli/roleset/lambda_role'
  vaultAzureRole: 'azure/carlli/roles/lambda_role'
  emailSubs:
    - 'carl.li@mantelgroup.com.au'
  tags:
    DoNotNuke: 'true'
