lambdaProps:
  checkBillCron: 0 22 ? * SUN *
  gcpBillTableId: 'ctg-storage.bigquery_billing_export.gcp_billing_export_v1_01150A_B8F62B_47D999' # gcp sample billing data for query
  vaultUrl: http://example.com.au:8200
  vaultAWSRole: 'aws/sandpit1/roles/lambda_role'
  vaultGCPRoleSet: 'gcp/sandpit1/roleset/lambda_role'
  vaultAzureRole: 'azure/sandpit1/roles/lambda_role'
  emailSubs:
    - 'john@example.com'
